// <auto-generated />
using Desafio_NO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Desafio_NO.Migrations
{
    [DbContext(typeof(AdressContext))]
    partial class AdressContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Desafio_NO.Models.Entities.AdressTable", b =>
                {
                    b.Property<string>("cep")
                        .HasColumnType("text");

                    b.Property<string>("bairro")
                        .HasColumnType("text");

                    b.Property<string>("complemento")
                        .HasColumnType("text");

                    b.Property<string>("ddd")
                        .HasColumnType("text");

                    b.Property<string>("gia")
                        .HasColumnType("text");

                    b.Property<string>("ibge")
                        .HasColumnType("text");

                    b.Property<string>("localidade")
                        .HasColumnType("text");

                    b.Property<string>("logradouro")
                        .HasColumnType("text");

                    b.Property<string>("siafi")
                        .HasColumnType("text");

                    b.Property<string>("uf")
                        .HasColumnType("text");

                    b.HasKey("cep");

                    b.ToTable("Adress_RL");
                });
#pragma warning restore 612, 618
        }
    }
}
